name: mpflutter_plugin_template
description: The MPFlutter plugin template.
publish_to: none
version: 0.0.1
homepage: /

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter: 
    hosted:
      name: flutter
      url: https://pub.mpflutter.com
  mpcore: 
    hosted:
      name: mpcore
      url: https://pub.mpflutter.com
  
dependency_overrides:
  flutter: 
    hosted:
      name: flutter
      url: https://pub.mpflutter.com
  mpcore: 
    hosted:
      name: mpcore
      url: https://pub.mpflutter.com